(function e(t,n,r){function s(o,u){if(!n[o]){if(!t[o]){var a=typeof require=="function"&&require;if(!u&&a)return a(o,!0);if(i)return i(o,!0);var f=new Error("Cannot find module '"+o+"'");throw f.code="MODULE_NOT_FOUND",f}var l=n[o]={exports:{}};t[o][0].call(l.exports,function(e){var n=t[o][1][e];return s(n?n:e)},l,l.exports,e,t,n,r)}return n[o].exports}var i=typeof require=="function"&&require;for(var o=0;o<r.length;o++)s(r[o]);return s})({1:[function(require,module,exports){
function generateEdges(r){for(var t=r.data,e=r.width,n=r.height,a=new Uint32Array(2*(e-1)*(n-1)),o=0,u=0;u<e-1;++u)for(var g=0;g<n-1;++g){var i=g*e+u,c=calculateWeight(t,i,i+1);a[o++]=c<<20|i;c=calculateWeight(t,i,i+e);a[o++]=c<<20|1<<19|i}return a}function calculateWeight(r,t,e){t<<=2;var n=r[e<<=2]-r[t],a=r[e+1]-r[t+1],o=r[e+2]-r[t+2],u=n*n+a*a+o*o>>4;return u<=1023?u:1023}function countingSort(r,t){for(var e=[],n=0,a=r.length;n<a;++n){var o=r[n],u=o>>>t;e[u]||(e[u]=[]),e[u].push(o)}for(var g=0,n=0;n<e.length;++n){var i=e[n];if(i)for(var c=i.length;c--;)r[g++]=i[c]}return r}module.exports=function(r){var t=generateEdges(r);return countingSort(t,20),t};

},{}],2:[function(require,module,exports){
"use strict";function union(r,t,e){var i=t*structSize,n=e*structSize;if(r[i]<r[n]){var a=i;i=n,n=a,a=t,t=e,e=a}r[i]===r[n]&&r[i]++,r[n+1]=t,r[i+2]+=r[n+2],r[i+3]+=r[n+3],r[i+4]+=r[n+4],r[i+5]+=r[n+5]}function find(r,t){for(var e=t;r[n=t*structSize+1]!==t;)t=r[n];var i=t;for(t=e;;){var n=t*structSize+1;if(r[n]===t)break;t=r[n],r[n]=i}return i}function myDistance(r,t,e){var i=t*structSize,n=e*structSize,a=1/r[i+2],u=a*r[i+3],o=a*r[i+4],c=a*r[i+5],s=1/r[n+2],f=u-s*r[n+3],v=o-s*r[n+4],g=c-s*r[n+5];return f*f+v*v+g*g}function segmentation(r,t,e){for(var i=r.data,n=r.width,a=r.height,u=n*a,o=new Int32Array(structSize*u),c=0;c<u;++c){var s=i[m=4*c],f=i[m+1],v=i[m+2],g=structSize*c;o[g+1]=c,o[g+2]=1,o[g+3]=s,o[g+4]=f,o[g+5]=v}for(var m=0;m<t.length;++m){var z=t[m],S=524287&z,d=524288&z?S+n:S+1;(S=find(o,S))!==(d=find(o,d))&&(myDistance(o,S,d)<e&&union(o,S,d))}return r.data.set(avgColorImage(o,n,a)),r}function avgColorImage(r,t,e){for(var i=new Uint8ClampedArray(4*t*e),n=0;n<t*e;++n){var a=find(r,n)*structSize,u=1/r[a+2];i[4*n]=u*r[a+3],i[4*n+1]=u*r[a+4],i[4*n+2]=u*r[a+5],i[4*n+3]=255}return i}var imageGraph=require("./imagegraph"),structSize=6;module.exports=function(r,t){return segmentation(r,imageGraph(r),t)};

},{"./imagegraph":1}],3:[function(require,module,exports){
"use strict";var segmentation=require("./segmentation");self.addEventListener("message",function(e){var a=e.data.imageData,t=new Date;a=segmentation(a,e.data.threshold),self.postMessage({imageData:a,time:new Date-t})},!1);

},{"./segmentation":2}]},{},[3]);
